# Generated by Django 4.0.3 on 2022-04-18 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itineraires', '0002_itineraire_delete_itinineraire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date de la sortie')),
                ('duree_reelle', models.DurationField(verbose_name='Durée réelle de la sortie')),
                ('nb_personnes', models.IntegerField(default=1, verbose_name='Nombre de personnes ayant participé à la sortie')),
                ('experience', models.CharField(choices=[('Tous débutants', 'Tous débutants'), ('Groupe mixte', 'Groupe mixte'), ('Tous expérimentés', 'Tous expérimentés')], max_length=50, verbose_name='Experience du groupe')),
                ('meteo', models.CharField(choices=[('Mauvaise', 'Mauvaise'), ('Moyenne', 'Moyenne'), ('Bonne', 'Bonne')], max_length=50)),
                ('difficulte', models.IntegerField(choices=[(1, '1 - Très facile'), (2, '2 - Facile'), (3, '3 - Modérée'), (4, '4 - Difficile'), (5, '5 - Très difficile')], verbose_name='Difficulté ressentie')),
                ('itineraire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itineraires.itineraire')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
